#!/bin/bash

# STORE THIS AS /usr/local/bin/sysbacklight
# And update permissions in sudoers to run this

# CHANGE THIS: What my backlight vendor is
sysfs="/sys/class/backlight/radeon_bl0/"

usage()
{
    script=${0##*/}
    echo
    echo "Usage of ${script}: "
    echo "----------------"
    echo "$script up     : increases brightness"
    echo "$script down   : decreases brightness"
    echo "$script set #  : sets brightness to # (integer)"
    echo "----------------"
    echo
    echo "Error: $1"

    exit 1
}

# Max possible and current brightness
max=`cat ${sysfs}/max_brightness`
level=`cat ${sysfs}/brightness`

set_brightness()
{
    level=$1
    if [ $level -lt 1 ] ; then
        level=1
    elif [ $level -gt $max ] ; then
        level=$max
    fi

    echo $level > $sysfs/brightness
}

case "$1" in 
    up)
        let "level+=25"
        set_brightness $level
        ;;
    down)
        let "level-=25"
        set_brightness $level
        ;;
    set)
        if [[ ! $2 =~ ^[[:digit:]]+$ ]]; then
            usage "second argument to set must be an integer"
        fi
        set_brightness $2
        ;;
    *)
        usage "invalid argument $1"
esac

