#!/bin/bash

typeset -i num_batteries=$(acpi | wc -l)

output=""

for (( i = 1; i <= $num_batteries; ++i ))
do
    charge_status="$(acpi --battery | cut -d ' ' -f 3 | tr -d ,% | sed -n ${i}p)"
    percentage="$(acpi --battery | cut -d ' ' -f 4 | tr -d ,% | sed -n ${i}p)"

    if [ "${charge_status}" == "Discharging" ]
    then
        output+="-""${percentage}"
    elif [ "${charge_status}" == "Charging" ]
    then
        output+="+""${percentage}"
    elif [ "${charge_status}" == "Full" ]
    then
        output+="~""${percentage}"
    elif [ "${charge_status}" == "Unknown" ]
    then
        output+="*""${percentage}"
    else
        output+="?"
    fi
    output+=" "
done

echo ${output}
