#!/bin/bash

# There are two batteries on the Thinkpad, using `head -1` to only get the main
# battery status.
charge_status="$(acpi --battery | cut -d ' ' -f 3 | tr -d ,% | head -1)"
percentage="$(acpi --battery | cut -d ' ' -f 4 | tr -d ,% | head -1)"

# Discharging/Full/Charging
if [ "${charge_status}" == "Discharging" ]
then
    echo "-""${percentage}"
elif [ "${charge_status}" == "Charging" ]
then
    echo "+""${percentage}"
elif [ "${charge_status}" == "Full" ]
then
    echo "~""${percentage}"
else
    echo "?"
fi
